#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# KubeChat — GCP VM Auto-Setup Script
# Run this on a fresh GCP e2-micro VM (Ubuntu 22.04)
# 
# Usage:
#   curl -sSL https://raw.githubusercontent.com/mittal122/kubechat-microservices/master/gcp-setup.sh | bash
#   OR: bash gcp-setup.sh
# ═══════════════════════════════════════════════════════════════

set -e  # Exit on any error

# ── Colors ──────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

print_step() { echo -e "\n${CYAN}══ $1 ══${NC}"; }
print_ok()   { echo -e "${GREEN}  ✅ $1${NC}"; }
print_warn() { echo -e "${YELLOW}  ⚠️  $1${NC}"; }
print_info() { echo -e "  ℹ️  $1"; }

# ── CONFIGURATION — Edit these before running ───────────────────
REPO_URL="https://github.com/mittal122/kubechat-microservices.git"
DEPLOY_DIR="/opt/kubechat"

# ── Your environment variables — FILL THESE IN ──────────────────
MONGO_URI="mongodb+srv://mittalaws_db_user:Mittal0000@kubechat.v1nj0sh.mongodb.net/chatApp?appName=kubechat"
REDIS_URL="rediss://default:gQAAAAAAAa06AAIgcDE0YmI3ZjQ4YTA5ZDQ0NjU5YjEzMDAyZDgzOGRhOGVkZA@amusing-trout-109882.upstash.io:6379"
JWT_SECRET="2c1575d2bba5e21c5554d09a03f365e72f75fd8736626b42a6d2461d40b2fbc46eaa9ef29497818f247ca48e0c2e7a0dfdc624e501c30433fdcfebf3062ef61c"
# ────────────────────────────────────────────────────────────────

echo ""
echo "  ██╗  ██╗██╗   ██╗██████╗ ███████╗ ██████╗██╗  ██╗ █████╗ ████████╗"
echo "  ██║ ██╔╝██║   ██║██╔══██╗██╔════╝██╔════╝██║  ██║██╔══██╗╚══██╔══╝"
echo "  █████╔╝ ██║   ██║██████╔╝█████╗  ██║     ███████║███████║   ██║   "
echo "  ██╔═██╗ ██║   ██║██╔══██╗██╔══╝  ██║     ██╔══██║██╔══██║   ██║   "
echo "  ██║  ██╗╚██████╔╝██████╔╝███████╗╚██████╗██║  ██║██║  ██║   ██║   "
echo "  ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝  "
echo ""
echo "  GCP Auto-Setup Script"
echo "  ======================================================"

# ── STEP 1: Update system ────────────────────────────────────────
print_step "Step 1/5: Updating system packages"
sudo apt-get update -qq
sudo apt-get upgrade -y -qq
print_ok "System updated"

# ── STEP 2: Install Docker ───────────────────────────────────────
print_step "Step 2/5: Installing Docker"
if command -v docker &> /dev/null; then
    print_ok "Docker already installed ($(docker --version))"
else
    print_info "Installing Docker..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo usermod -aG docker $USER
    rm get-docker.sh
    print_ok "Docker installed"
fi

# Install Docker Compose plugin
if docker compose version &> /dev/null; then
    print_ok "Docker Compose already installed"
else
    print_info "Installing Docker Compose..."
    sudo apt-get install -y docker-compose-plugin -qq
    print_ok "Docker Compose installed"
fi

# ── STEP 3: Clone repository ─────────────────────────────────────
print_step "Step 3/5: Setting up project"
if [ -d "$DEPLOY_DIR" ]; then
    print_info "Project exists — pulling latest changes..."
    cd $DEPLOY_DIR
    sudo git pull origin master
else
    print_info "Cloning repository..."
    sudo git clone $REPO_URL $DEPLOY_DIR
    cd $DEPLOY_DIR
fi
sudo chown -R $USER:$USER $DEPLOY_DIR
print_ok "Repository ready at $DEPLOY_DIR"

# ── STEP 4: Create .env file ─────────────────────────────────────
print_step "Step 4/5: Creating environment configuration"
cat > $DEPLOY_DIR/.env << EOF
# KubeChat Production Environment
# Generated by gcp-setup.sh

MONGO_URI=${MONGO_URI}
REDIS_URL=${REDIS_URL}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=production
CORS_ORIGIN=*

# Service URLs (internal Docker network)
AUTH_SERVICE_URL=http://auth-service:5001
USER_SERVICE_URL=http://user-service:5002
CHAT_SERVICE_URL=http://chat-service:5003
EOF
print_ok ".env file created"

# ── STEP 5: Start services ───────────────────────────────────────
print_step "Step 5/5: Starting KubeChat services"
cd $DEPLOY_DIR
sudo docker compose -f docker-compose.prod.yml up -d --build 2>&1

print_info "Waiting 15 seconds for services to initialize..."
sleep 15

# Health check
if curl -sf http://localhost:5000/health > /dev/null 2>&1; then
    print_ok "API Gateway is healthy!"
else
    print_warn "Health check timed out — services may still be starting (normal on first run)"
fi

# Get external IP
EXTERNAL_IP=$(curl -sf http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip -H "Metadata-Flavor: Google" 2>/dev/null || echo "unknown")

echo ""
echo "  ======================================================"
echo -e "  ${GREEN}✅ KubeChat is LIVE!${NC}"
echo "  ======================================================"
echo ""
echo "  Your server URL: http://${EXTERNAL_IP}:5000"
echo "  Health check:    http://${EXTERNAL_IP}:5000/health"
echo ""
echo "  Next steps:"
echo "  1. Update flutter_chat_app/lib/config/api_config.dart"
echo "     with URL: http://${EXTERNAL_IP}:5000"
echo "  2. Rebuild APK: flutter build apk --release --dart-define=ENV=production"
echo "  3. Install APK on your phone"
echo ""
echo "  To stop:   cd /opt/kubechat && docker compose down"
echo "  To restart: cd /opt/kubechat && docker compose up -d"
echo "  To view logs: docker compose logs -f"
echo "  ======================================================"
