apiVersion: v1
kind: Secret
metadata:
  name: kubechat-secrets
type: Opaque
stringData:
  # ⚠️ Replace these with your actual production database URLs before applying!
  MONGO_URI: "mongodb+srv://..."
  JWT_SECRET: "kubechat_super_secret_jwt_key_2024"
  REDIS_URL: "rediss://..."
